export const offers = [
  { id: "on-sale", label: "On Sale" },
  { id: "new-arrivals", label: "New Arrivals" },
  { id: "clearance", label: "Clearance" },
];

export const brands = [
  { id: "pawsitive-wellness", label: "Pawsitive Wellness" },
  { id: "happy-tails-outfitters", label: "Happy Tails Outfitters" },
  { id: "aquafun-comforts", label: "AquaFun Comforts" },
  { id: "wildbites", label: "WildBites" },
  { id: "feathernest-homes", label: "FeatherNest Homes" },
  { id: "gregarious-co", label: "Gregarious Co." },
];

export const dummyProducts = [
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 1",
    description: "Product 1 description",
    price: 100,
    rating: 4.1,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Food",
    petType: "Dogs",
    brandType: "Pawsitive Wellness",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 2",
    description: "Product 2 description",
    price: 7.99,
    rating: 3,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 3",
    description: "Product 3 description",
    price: 200,
    rating: 2.5,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 4",
    description: "Product 4 description",
    price: 105.99,
    rating: 3.7,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 5",
    description: "Product 5 description",
    price: 33.99,
    rating: 3,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Yasuo",
    description: "Product Yasuo description",
    price: 65.99,
    rating: 4.8,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Fish Tanks",
    petType: "Dogs",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Vitamin 69",
    description: "Vitamin 69 description",
    price: 69.99,
    rating: 4.9,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 2",
    description: "Product 2 description",
    price: 15.99,
    rating: 3,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Cages",
    petType: "Dogs",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "GUINEAS",
    description: "GUINEAS Production description",
    price: 119.99,
    rating: 3,
    inStock: false,
    offersType: "On Sale",
    productType: "Toys",
    petType: "Cats",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 2",
    description: "Product 2 description",
    price: 49.99,
    rating: 1.2,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Donkey",
    description: "Donk description",
    price: 17.99,
    rating: 3,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Shrek",
    description: "Shrek Production",
    price: 48.99,
    rating: 2.4,
    inStock: true,
    offersType: "On Sale",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Product 2",
    description: "Product 2 description",
    price: 99.99,
    rating: 5,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Hard Food",
    description: "Hard description",
    price: 22.99,
    rating: 4.3,
    inStock: false,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Wet Food",
    description: "Wet description",
    price: 19.99,
    rating: 3,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Dry Food",
    description: "Dry description",
    price: 69.99,
    rating: 2.2,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Cat",
    brandType: "Happy Tails Outfitters",
  },
  {
    image:
      "https://s3-pet-supplies-app-v1.s3.ca-west-1.amazonaws.com/donkey1.jpg",
    name: "Gregarious",
    description: "El Pachonaso",
    price: 499.99,
    rating: 5,
    inStock: true,
    offersType: "New Arrivals",
    productType: "Toys",
    petType: "Guinea Pigs",
    brandType: "Gregarious Co.",
  },
];
